Hardcode azure-mgmt-dns version to 8.2.0
New version of azure-mgmt-dns library (9.0.0) was released 2025-07-14. This version has several breaking changes, the one I hit was in DnsManagementClient initialisation.
This class no longer has same fields, which causes following exception in certbot-dns-azure-plugin:

'''
Encountered exception during recovery: TypeError: DnsManagementClient.__init__() takes from 3 to 4 positional arguments but 5 were given
An unexpected error occurred:
TypeError: DnsManagementClient.__init__() takes from 3 to 4 positional arguments but 5 were given
'''

Signed-off-by: boris.petrovic <boris.petrovic@netronix.rs>